# Generated by Django 5.2.14 on 2026-06-02 13:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusyBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('kind', models.CharField(choices=[('manual', 'Manual'), ('break', 'Break')], default='manual', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='busy_blocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_at'],
                'indexes': [models.Index(fields=['user', 'start_at'], name='bblock_user_start_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_at__gt', models.F('start_at'))), name='busy_block_positive_duration')],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('duration_minutes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(600)])),
                ('priority', models.CharField(choices=[('low', 'Low'), ('med', 'Med'), ('high', 'High')], default='med', max_length=10)),
                ('energy', models.CharField(choices=[('low', 'Low'), ('med', 'Med'), ('high', 'High')], default='med', max_length=10)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('body_double_preferred', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('done', 'Done'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=15)),
                ('scheduled_start', models.DateTimeField(blank=True, null=True)),
                ('actual_start_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent_minutes', models.PositiveSmallIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_start', 'created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='task_user_status_idx'), models.Index(fields=['user', 'scheduled_start'], name='task_user_sched_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'in_progress')), fields=('user',), name='one_task_in_progress_per_user'), models.CheckConstraint(condition=models.Q(('duration_minutes__gte', 5), ('duration_minutes__lte', 600)), name='task_duration_bounds')],
            },
        ),
    ]
