# Generated by Django 5.2.14 on 2026-05-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=48)),
                ('post_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-post_count', 'name'],
                'indexes': [models.Index(fields=['-post_count'], name='tags_tag_post_co_b0c18d_idx')],
            },
        ),
    ]
