# Generated by Django 5.2.14 on 2026-06-02 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyDoubleSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_id', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended')], default='active', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('user_a', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='body_double_sessions_as_a', to=settings.AUTH_USER_MODEL)),
                ('user_b', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='body_double_sessions_as_b', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PoolTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('matched', 'Matched'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='waiting', max_length=10)),
                ('matched_with', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_pair', to='body_double.poolticket')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='body_double.bodydoublesession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_double_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bodydoublesession',
            index=models.Index(fields=['-started_at'], name='body_double_started_5370be_idx'),
        ),
        migrations.AddIndex(
            model_name='bodydoublesession',
            index=models.Index(fields=['status', '-started_at'], name='body_double_status_718616_idx'),
        ),
        migrations.AddIndex(
            model_name='poolticket',
            index=models.Index(fields=['status', 'created_at'], name='body_double_status_b2fdcc_idx'),
        ),
        migrations.AddConstraint(
            model_name='poolticket',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['waiting', 'matched'])), fields=('user',), name='one_active_ticket_per_user'),
        ),
    ]
