# Generated by Django 5.2.14 on 2026-06-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body_double', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poolticket',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('matched', 'Matched'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='waiting', max_length=10),
        ),
    ]
