# Generated by Django 5.2.14 on 2026-06-02 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body_double', '0002_alter_poolticket_status'),
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poolticket',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pool_tickets', to='communities.community'),
        ),
    ]
