# Generated by Django 5.2.14 on 2026-06-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body_double', '0003_poolticket_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodydoublesession',
            name='agreed_duration_minutes',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Min of the two tickets' duration_minutes at match time. Shown as a static label in the room — no auto-end.", null=True),
        ),
        migrations.AddField(
            model_name='poolticket',
            name='chattiness',
            field=models.CharField(choices=[('chatty', 'Chatty — happy to talk between focus'), ('quiet', 'Quiet — silent focus'), ('flexible', "Flexible — either's fine")], default='flexible', help_text='Conversational preference. Hard compat rule in the matcher.', max_length=10),
        ),
        migrations.AddField(
            model_name='poolticket',
            name='duration_minutes',
            field=models.PositiveSmallIntegerField(choices=[(15, '15 min'), (30, '30 min'), (45, '45 min'), (60, '60 min'), (90, '90 min')], default=30, help_text='Expected session length. Matcher prefers nearby durations.'),
        ),
        migrations.AddField(
            model_name='poolticket',
            name='work_mode',
            field=models.CharField(choices=[('deep_focus', 'Deep focus'), ('busywork', 'Busywork'), ('admin', 'Admin / email'), ('any', 'Any')], default='any', help_text="What you're working on. Soft preference; loosens over time.", max_length=15),
        ),
    ]
