# Generated by Django 5.2.14 on 2026-06-10 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body_double', '0004_bodydoublesession_agreed_duration_minutes_and_more'),
        ('communities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_at', models.DateTimeField(db_index=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(choices=[(15, '15 min'), (30, '30 min'), (45, '45 min'), (60, '60 min'), (90, '90 min')], default=30, help_text='Planned session length from start_at.')),
                ('chattiness', models.CharField(choices=[('chatty', 'Chatty — happy to talk between focus'), ('quiet', 'Quiet — silent focus'), ('flexible', "Flexible — either's fine")], default='flexible', help_text='Conversational preference. Hard compat rule in the matcher.', max_length=10)),
                ('work_mode', models.CharField(choices=[('deep_focus', 'Deep focus'), ('busywork', 'Busywork'), ('admin', 'Admin / email'), ('any', 'Any')], default='any', help_text="What you're working on. Affects partner ranking only.", max_length=15)),
                ('status', models.CharField(choices=[('open', 'Open'), ('matched', 'Matched'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='open', max_length=10)),
                ('agreed_start_at', models.DateTimeField(blank=True, null=True)),
                ('agreed_end_at', models.DateTimeField(blank=True, null=True)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_bookings', to='communities.community')),
                ('matched_with', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_pair', to='body_double.scheduledbooking')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='body_double.bodydoublesession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_double_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_at'],
                'indexes': [models.Index(fields=['status', 'start_at'], name='body_double_status_fca20a_idx'), models.Index(fields=['user', 'start_at'], name='body_double_user_id_f701d1_idx')],
            },
        ),
    ]
