# Generated by Django 5.2.14 on 2026-06-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body_double', '0005_scheduledbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='poolticket',
            name='friends_only',
            field=models.BooleanField(default=False, help_text='Only match with people on my friends list.'),
        ),
    ]
