# Generated by Django 5.2.14 on 2026-06-02 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('layer', models.CharField(choices=[('L1', 'Keyword (L1)'), ('L2', 'Claude (L2)')], max_length=4)),
                ('surface', models.CharField(choices=[('comment', 'Comment body'), ('post_body', 'Post body'), ('post_title', 'Post title')], max_length=20)),
                ('text', models.TextField(help_text='The exact content that was blocked.')),
                ('reason', models.TextField(help_text='User-facing rejection message shown at submit time.')),
                ('false_positive', models.BooleanField(default=False, help_text='Admin-marked: this should not have been blocked. Use to track tuning needs (e.g. add the term to an allowlist).')),
                ('author', models.ForeignKey(blank=True, help_text='The user who tried to submit the content. May be null if the form was constructed without an author reference.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderation_blocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'moderation log entry',
                'verbose_name_plural': 'moderation log',
                'indexes': [models.Index(fields=['-created_at'], name='moderation__created_5b13b7_idx'), models.Index(fields=['author', '-created_at'], name='moderation__author__824082_idx'), models.Index(fields=['layer', '-created_at'], name='moderation__layer_3a4bc6_idx')],
            },
        ),
    ]
